openapi: 3.0.0

info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080
    description: local
  
paths:

  /api/user/create:
    post:
      summary: Create a new user
      parameters:
        - name: body
          in: body
          required: true
          schema:
            # Body schema with atomic property examples
            type: object
            properties:
              username:
                type: string
                example: test@user.com
              password:
                type: string
                example: password1234
              tcno:
                type: string
                example: 12512561125          
      responses: 
        '200':
          description: 'create a new user'
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    description: Username
                  tcno:
                    type: string
                    description: ID