name: developer-hub-ci

on:
  pull_request:
    types: [opened, reopened]
      
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build

     