name: example-rtl-cd

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md"
          allow_failure: false

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: open-api-spec.yml

  performance: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: kSixLoadTest.js
      
      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: summary.json


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Scan for committed credentials
        id: scan-for-creds
        run: |
          pip install gittyleaks
          gittyleaks
         
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



