name: example-rtl-cd

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "README.md"
          # weird that this is set to true - there is a git issue logged
          # https://github.com/andstor/file-existence-action/issues/7
          allow_failure: true

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: open-api-spec.yml
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Test with Maven
        run: mvn test


  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t demo/bankapp .

  performance: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: kSixLoadTest.js
      
      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-summary-report
          path: summary.json


  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Scan for committed credentials
        id: scan-for-creds
        run: |
          pip install gittyleaks
          gittyleaks
         
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



